### ISSUE TITLE
Cannot find symbol 'createDefaultEndpoint()'

### ISSUE THREAD

**Issue by tomglvng** [mslosarz/nextrtc-example-wo-spring#1]
Hello,

I downloaded 'nextrtc-example-wo-spring' and created a new NetBeans project (new Maven project -> project from existing DOM) .
When I build it, I have the following error:
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project nextrtc-example-wo-spring: Compilation failure
org/nextrtc/examples/videochat/MyEndpoint.java:[24,54] cannot find symbol
The error is the following line in 'MyEndpoint.java':
 EndpointConfiguration configuration = builder.createDefaultEndpoint();

Could you tell me what is wrong?

Regards,

**Comment by mslosarz** [comment]
Fixed :)
I've deployed new version as a release candidate. Previous one (1.0.0-SNAPSHOT) has been deployed long time ago to sonatype, so maven has taken wrong version of library.

So please checkout current version, and try it now

**Comment by tomglvng** [comment]
Dziękuję bardzo!
