### ISSUE TITLE
Something goes wrong! undefined

### ISSUE THREAD

**Issue by tomglvng** [mslosarz/nextrtc-example-wo-spring#2]
Hello,

I have an issue when trying to connect to my local server, the following message appears under "Conversation id" field:
"Something goes wrong! undefined"

It seems to be an issue in "index.html".

my 'wsURL" configuration:
'wss://127.0.0.1:8433/nextrtc-example-wo-spring/signaling'

Run on Tomcat 8.0.27.0 (Integrated version in Netbeans 8.2).

Do you have any idea what is going wrong?

Thanks in advance,

**Comment by tomglvng** [comment]
Fixed: bad configuration :(

**Comment by dampa92** [comment]
Hi man
I have the same error. How did you resolve it?
I have tried to fix configuration but no result.
Thanks
