### ISSUE TITLE
code doesn't compile when updating to nextrtc-signaling-server to RC3

### ISSUE THREAD

**Issue by LorenzoMcMaster** [mslosarz/nextrtc-example-wo-spring#3]
INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /opt/nextrtc-example-wo-spring-master/src/main/java/org/nextrtc/examples/videochat/MyEndpoint.java:[32,25] cannot find symbol
  symbol:   method send()
  location: class org.nextrtc.signalingserver.domain.InternalMessage

**Comment by mslosarz** [comment]
I've introduced one braking change (send method is not available now) I'll push update soon.

**Comment by mslosarz** [comment]
It's fixed now. Please pull changes and have a fun
